### ISSUE TITLE
Support for Godot 4.x version

### ISSUE THREAD

**Issue by piszczu4** [matterda/godot-destructible-terrain#1]
Hi, is it project still maintained? I'm looking for exactly this feature for my Godot 4.3 project but this code is for 3.x version. Any change to get updated version?

**Comment by mattiarovetta-vd** [comment]
I haven't touched GDScript or Godot in ages, so I don't think I will update it. Try this fork instead: https://github.com/ArcturusForge/godot-destructible-terrain

**Comment by matterda** [comment]
I haven't touched GDScript or Godot in ages, so I don't think I will update it. Try this fork instead: https://github.com/ArcturusForge/godot-destructible-terrain
